const express = require("express");
const router = express.Router();
const adminController = require("../controllers/AdminController");
const { storage, upload } = require("./lib/multer");
router.get("/addProduct", adminController.showProduct);
router.post("/addProduct", adminController.addProduct);
router.get("/:id/edit", adminController.editProduct);
router.put("/:id", upload.single("image"), adminController.updateProduct);
router.get("/", adminController.admin);
module.exports = router;
