const express = require("express");
const router = express.Router();
const LabController = require("../controllers/LabController");
router.get("/cate/:id", LabController.cate);
router.get("/getOutstandingProducts", LabController.getOutstandingProducts);
router.get("/getProductLimit", LabController.getProductLimit);
router.get("/searchProduct", LabController.searchProduct);
router.get("/getProductListIncreasePrice", LabController.getProductListIncreasePrice);
router.get("/getRelatedProducts", LabController.getRelatedProducts);
router.delete("/findAndDeleteItem/:id", LabController.findAndDeleteItem);
router.get("/productsManyViews", LabController.productsManyViews);
router.get("/", LabController.lab);
module.exports = router;
